sonweb/Models/TeamMember.cs
using System.ComponentModel.DataAnnotations;

namespace sonweb.Models
{
    public class TeamMember
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Boş ola bilməz"), MaxLength(50, ErrorMessage = "Uzunluq maximum 50 simvol olmalıdır")]
        public string FullName { get; set; }
        [Required]
        public string Profession { get; set; }//ixtisasi
        [Required]
        public string ImagePath { get; set; }
    }
}

sonweb/Areas/Admin/Controllers/TeamMemberController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using sonweb.Areas.Admin.ViewModels;
using sonweb.DAL;
using sonweb.Models;
using sonweb.Utilities.Constrants;
using sonweb.Utilities.Extensions;

namespace sonweb.Areas.Admin.Controllers
{


    [Area("Admin")]
    public class TeamMemberController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public TeamMemberController(AppDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public async Task<IActionResult> Index()
        {
            ICollection<TeamMember> members = await _context.TeamMembers.ToListAsync();
            return View(members);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateTeamMemberVM member)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            if (!member.Photo.CheckContentType("image/"))
            {
                ModelState.AddModelError("Photo", $"{member.Photo.FileName} {Messages.FileTypeMustBeImage}");
                return View();
            }
            if (!member.Photo.CheckFileSize(200))
            {
                ModelState.AddModelError("Photo", $"{member.Photo.FileName} - file type must be size less than 200kb");
                return View();
            }
            string root = Path.Combine(_webHostEnvironment.WebRootPath, "assets", "img");

            string fileName = await member.Photo.SaveAsync(root);
            TeamMember teamMember = new TeamMember()
            {
                FullName = member.FullName,
                ImagePath = fileName,
                Profession = member.Profession
            };
            await _context.TeamMembers.AddAsync(teamMember);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int id)
        {
            TeamMember member = await _context.TeamMembers.FindAsync(id);
            if (member == null) return NotFound();
            return View(member);
        }

        [HttpPost]
        public async Task<IActionResult> Update(TeamMember member)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            TeamMember result = await _context.TeamMembers.FirstOrDefaultAsync(t => t.Id == member.Id);
            if (result is null)
            {
                TempData["Exists"] = "Bu Member bazada yoxdur";
                return RedirectToAction(nameof(Index));
            }
            result.FullName = member.FullName;
            result.Profession = member.Profession;
            result.ImagePath = member.ImagePath;
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            TeamMember teamMember = await _context.TeamMembers.FindAsync(id);
            if (teamMember == null) return NotFound();
            string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "assets", "img", teamMember.ImagePath);
            if (System.IO.File.Exists(imagePath))
            {
                System.IO.File.Delete(imagePath);
            }

            _context.TeamMembers.Remove(teamMember);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

sonweb/Areas/Admin/Views/TeamMember/Create.cshtml
@model CreateTeamMemberVM
@{
    ViewData["Title"] = "Create";
}

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">

            <form class="forms-sample" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="FullName"></label>
                    <input asp-for="FullName" class="form-control" placeholder="Full Name">
                    <span class="text text-danger" asp-validation-for="FullName"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Profession"></label>
                    <input asp-for="Profession" class="form-control" placeholder="Profession">
                    <span class="text text-danger" asp-validation-for="Profession"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Photo"></label>
                    <input asp-for="Photo" class="form-control" placeholder="Photo">
                    <span class="text text-danger" asp-validation-for="Photo"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2 text-light">Create</button>
                <button class="btn btn-light" asp-action="Index">Go back</button>

            </form>
        </div>
    </div>

sonweb/Areas/Admin/Views/TeamMember/Index.cshtml
@model List<TeamMember>
@{
    ViewData["Title"] = "TeamMembers";
    int count = 1;
}

<span class=" alert alert-warning">@TempData["Exists"]</span>
<div class="d-flex justify-content-end mb-2">
    <a class="btn btn-success text-light" asp-area="Admin" asp-controller="TeamMember" asp-action="Create">Create Member</a>
</div>
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Number
                            </th>
                            <th>
                                Full Name
                            </th>
                            <th>
                                Profession
                            </th>
                            <th>
                                Image
                            </th>

                        </tr>
                    </thead>
                    <tbody>

                        @foreach (TeamMember item in Model)
                        {
                            <tr>
                                <td> @count</td>

                                <td>
                                    @item.FullName
                                </td>
                                <td>
                                    @item.Profession
                                </td>
                                <td>
                                    <img src="~/assets/img/@item.ImagePath" style="height:150px; width:150px;"></img>
                                </td>
                                <td>
                                    <a class="btn btn-warning text-light" asp-area="Admin" asp-controller="TeamMember" asp-action="Update" asp-route-Id="@item.Id">
                                        <i class="mdi mdi-grease-pencil"></i>
                                    </a>
                                    <a class="btn btn-danger text-light" asp-area="Admin" asp-controller="TeamMember" asp-action="Delete" asp-route-Id="@item.Id">
                                        <i class="mdi mdi-delete-forever"></i>
                                    </a>
                                </td>
                            </tr>
                            count++;
                        }

                        @*<td>
                        <div class="progress">
                        <div class="progress-bar bg-success" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        </td>
                        <td>
                        $ 77.99
                        </td>
                        <td>
                        May 15, 2015
                        </td>*@

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

sonweb/Areas/Admin/Views/TeamMember/Update.cshtml
@model TeamMember
@{
    ViewData["Title"] = "Update";
}


<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">

            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="FullName"></label>
                    <input asp-for="FullName" class="form-control" placeholder="Full Name">
                    <span class="text text-danger" asp-validation-for="FullName"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Profession"></label>
                    <input asp-for="Profession" class="form-control" placeholder="Profession">
                    <span class="text text-danger" asp-validation-for="Profession"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImagePath"></label>
                    <input asp-for="ImagePath" class="form-control" placeholder="Image">
                    <span class="text text-danger" asp-validation-for="ImagePath"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2 text-light">Edit</button>
                <button class="btn btn-light" asp-action="Index">Go back</button>

            </form>
        </div>
    </div>
</div>